# Generated by Django 5.2.16 on 2026-07-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='blurred_storage_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
