# Generated by Django 5.2.16 on 2026-07-23 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('anonymous_session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('shot_limit', models.PositiveIntegerField()),
                ('shots_committed', models.PositiveIntegerField(default=0)),
                ('shots_reserved', models.PositiveIntegerField(default=0)),
                ('consent_version', models.CharField(default='', max_length=32)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
            ],
            options={
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['event', 'joined_at'], name='participant_event_i_6826dd_idx')],
            },
        ),
    ]
