# Generated by Django 5.2.16 on 2026-07-23 07:47

import apps.events.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(default='wedding', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('capturing', 'Capturing'), ('waiting', 'Waiting for reveal'), ('revealed', 'Revealed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('public_slug', models.SlugField(max_length=64, unique=True)),
                ('join_code', models.CharField(default=apps.events.models.generate_join_code, max_length=16, unique=True)),
                ('timezone_name', models.CharField(default='Europe/Berlin', max_length=64)),
                ('capture_starts_at', models.DateTimeField(blank=True, null=True)),
                ('capture_ends_at', models.DateTimeField(blank=True, null=True)),
                ('reveals_at', models.DateTimeField(blank=True, null=True)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('guest_capacity', models.PositiveIntegerField(default=5)),
                ('shots_per_guest', models.PositiveIntegerField(default=20)),
                ('visibility_mode', models.CharField(choices=[('immediate', 'Photos visible immediately'), ('own_only', 'Guests see only their own photos'), ('host_only', 'Host sees everything, guests wait'), ('hidden', 'Nobody sees anything until reveal')], default='hidden', max_length=20)),
                ('capture_mode', models.CharField(choices=[('camera_only', 'Camera only'), ('camera_and_upload', 'Camera and existing photos'), ('upload_only', 'Upload only')], default='camera_only', max_length=20)),
                ('guest_downloads_enabled', models.BooleanField(default=True)),
                ('face_lookup_enabled', models.BooleanField(default=False)),
                ('involves_minors', models.BooleanField(default=False)),
                ('retention_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('involves_minors', False), ('face_lookup_enabled', False), _connector='OR'), name='no_face_lookup_when_minors_involved')],
            },
        ),
    ]
