# Generated by Django 5.2.16 on 2026-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(choices=[('noon', 'Noon'), ('golden', 'Golden'), ('tungsten', 'Tungsten'), ('silver', 'Silver'), ('safelight', 'Safelight'), ('polar', 'Polar')], default='noon', max_length=20),
        ),
    ]
