# Generated by Django 5.2.16 on 2026-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='highlight_reel_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
