# Generated by Django 5.2.16 on 2026-07-23 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_highlight_reel_enabled_event_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blur_child_faces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('blur_child_faces', False), ('involves_minors', True), _connector='OR'), name='blur_child_faces_requires_minors_declared'),
        ),
    ]
