# Generated by Django 5.2.16 on 2026-07-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_blur_child_faces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reveal_withheld',
            field=models.BooleanField(default=False),
        ),
    ]
