# Generated by Django 5.2.16 on 2026-07-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincode',
            name='link_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
